[tool.poetry]
name = "pantograph"
version = "0.1.0"
description = "A machine-to-machine interaction system for Lean"
authors = ["Leni Aniva <v@leni.sh>"]
license = "GPL-3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pexpect = "^4.9.0"
torch = "2.2.1"
#vllm = "0.4.1"
openai = "1.30.5"

[tool.poetry.build]
generate-setup-file = false
script = "build.py"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
