[tool.poetry]
name = "pantograph"
version = "0.1.0"
description = "A machine-to-machine interaction system for Lean"
authors = ["Leni Aniva <v@leni.sh>"]
license = "GPL-3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pexpect = "^4.9.0"
torch = "2.2.1"
# vllm = "0.4.1"
fire = "0.6.0"
wandb = "0.17.0"
tenacity = "8.3.0"
sglang = "^0.1.16"
numpy = "^1.26.4"
openai = "^1.31.0"
tiktoken = "^0.7.0"

[tool.poetry.build]
generate-setup-file = false
script = "build.py"

[tool.poetry.group.dev.dependencies]
notebook = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
